platform :ios, '15.0'


use_frameworks!

def infobip_call_kit_pods

  pod 'InfobipCallKit', '1.0'
  pod 'RxSwift', '6.9.0'
  pod 'SnapKit', '5.7.1'
  pod 'SDWebImage', '5.21.7'
  pod 'XCoordinator', '2.2.1'
end

# Scene-based host.
target 'InfobipCallKitExample' do
  infobip_call_kit_pods
end

# Classic UIApplicationDelegate-only host.
target 'InfobipCallKitExampleAppDelegate' do
  infobip_call_kit_pods
end
